### ISSUE TITLE
[UPDATE] Update Documentation for Notifications - Behaviour Components

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [SyamSundarKirubakaran/android-jetpack#1]
Update the documentation by referring the video link,

- Notifications - [https://youtu.be/zGIw4MIJn5o](https://youtu.be/zGIw4MIJn5o)

Code of Conduct :
- Try to be as crisp as possible and try to follow the pattern that is followed for **Architecture Components** and keep the points clean.
- Screenshots can be taken from the associated video - if required.
- In the code section, comment out what every Line of Code does.

**Comment by Dragomegak** [comment]
It has been a while, but will you let me do this one?

**Comment by SyamSundarKirubakaran** [comment]
Sure, go on.! 👍
