### ISSUE TITLE
[UPDATE] Update Documentation for Wear OS - UI Components

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [SyamSundarKirubakaran/Android-Jetpack#12]
Update the documentation by referring the video link,

- Wear OS - [https://youtu.be/-F-llkD6cQY](https://youtu.be/-F-llkD6cQY)

Code of Conduct :
- Try to be as crisp as possible and try to follow the pattern that is followed for **Architecture Components** and keep the points clean.
- Screenshots can be taken from the associated video - if required.
- In the code section, comment out what every Line of Code does.

**Comment by Dragomegak** [comment]
If its possible can I take up the task?

**Comment by SyamSundarKirubakaran** [comment]
Yes you're up @Dragomegak
