### ISSUE TITLE
[UPDATE] Update Documentation for Emoji - UI Components

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [SyamSundarKirubakaran/Android-Jetpack#7]
Update the documentation by referring the video link,

- Emoji - [https://youtu.be/sYGKUtM2ga8](https://youtu.be/sYGKUtM2ga8)

Code of Conduct :
- Try to be as crisp as possible and try to follow the pattern that is followed for **Architecture Components** and keep the points clean.
- Screenshots can be taken from the associated video - if required.
- In the code section, comment out what every Line of Code does.

**Comment by MuchtarSalimov** [comment]
May I work on this?

**Comment by SyamSundarKirubakaran** [comment]
Sure @MuchtarSalimov , Go ahead.!

**Comment by SyamSundarKirubakaran** [comment]
Closed by @MuchtarSalimov
